var airports = [
  { value: "RKPC", label: "제주국제공항, 제주특별자치도 제주시 , CJU" },
  { value: "RKSI", label: "인천국제공항, 인천광역시 중구, SEL" },
  { value: "RKSS", label: "김포국제공항, 서울특별시 강서구,  SEL" },
  { value: "RKTN", label: "대구국제공항, 대구광역시 동구, TAE" },
  { value: "RKTU", label: "청주국제공항,충청북도 청주시, CJJ" },
  { value: "MDW", label: "무안국제공항, 전라남도 무안군, MWX" },
  { value: "RKJB", label: "John F. Kennedy International Airport, New York, MWX" },
  { value: "LGA", label: "La Guardia Airport, New York, NY" },
  { value: "IAD", label: "Washington Dulles International Airport, Washington, DC" },
  { value: "CDG", label: "Charles De Gaulle International Airport, Paris, France" },
  { value: "CGH", label: "Congonhas International Airport, Sao Paulo, Brazil" },
  { value: "CGK", label: "Soekarno-Hatta International Airport, Jakarta, Indonesia" },
  { value: "LHR", label: "London Heathrow Airport, London, United Kingdom" },
  { value: "FRA", label: "Frankfurt International Airport, Frankfurt, Germany" },
  { value: "HND", label: "Tokyo International Airport, Tokyo, Japan" },
];
